"""Generator for ``flamapy_feature_model.pyi`` — static typing for the descriptor-generated facade.

The facade synthesises its operation methods at runtime, so type checkers and IDEs cannot see them.
This module renders a ``.pyi`` stub from the same OperationDescriptors, giving autocomplete and
mypy the real signatures + return types. Run ``python -m flamapy.interfaces.python._stub`` to
regenerate; a test asserts the shipped stub matches this output so it never drifts.
"""
from typing import Any

from flamapy.core.discover import DiscoverMetamodels
from flamapy.core.operations import Input, OperationDescriptor

_HEADER = '''\
# Auto-generated by flamapy.interfaces.python._stub — do not edit by hand.
# Regenerate with: python -m flamapy.interfaces.python._stub
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

from flamapy.metamodels.configuration_metamodel.models import Configuration
from flamapy.metamodels.fm_metamodel.models import FeatureModel


class Backend(str, Enum):
    SAT = ...
    BDD = ...
    Z3 = ...
    SHARPSAT = ...


class FLAMAFeatureModel:
    model_path: str
    fm_model: FeatureModel
    backend: Optional[Backend]
    def __init__(self, model_path: str, backend: Optional[str] = ...) -> None: ...
'''


def _input_annotation(input_spec: Input) -> str:
    base = 'Any' if input_spec.type is Any else getattr(input_spec.type, '__name__', 'Any')
    if not input_spec.required and input_spec.default is None:
        return f'Optional[{base}]'
    return base


def _method_signature(descriptor: OperationDescriptor) -> str:
    params = ['self']
    for input_spec in descriptor.inputs:
        annotation = _input_annotation(input_spec)
        if input_spec.required:
            params.append(f'{input_spec.name}: {annotation}')
        else:
            params.append(f'{input_spec.name}: {annotation} = ...')
    if descriptor.selectable_backend:
        params.append('backend: Optional[str] = ...')
    return ', '.join(params)


def render_stub(operations: 'dict[str, OperationDescriptor] | None' = None) -> str:
    if operations is None:
        operations = DiscoverMetamodels().available_operations()
    lines = [_HEADER.rstrip('\n')]
    for name in sorted(operations):
        descriptor = operations[name]
        lines.append(
            f'    def {name}({_method_signature(descriptor)}) -> {descriptor.returns}: ...')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import os
    target = os.path.join(os.path.dirname(__file__), 'flamapy_feature_model.pyi')
    with open(target, 'w', encoding='utf-8') as handle:
        handle.write(render_stub())
    print(f'wrote {target}')
